### ISSUE TITLE
Python2 or Python3

### ISSUE THREAD

**Issue by zzatihz1** [ekul135/Powerwall2PVOutput#18]
I appreciate the updates to this script. I am getting errors but I think they may be related to the version of Python. Are these scripts Python2 or Python3 dependent? Thanks in advance!

**Comment by ekul135** [comment]
Python3


On 21 Feb 2021 at 8:05 am, zzatihz1 <notifications@github.com> wrote:

I appreciate the updates to this script. I am getting errors but I think
they may be related to the version of Python. Are these scripts Python2 or
Python3 dependent? Thanks in advance!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/ekul135/Powerwall2PVOutput/issues/18>, or unsubscribe
